// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7YyzxISjm8Jrl-9MTnPV84fJ8UBwSJCU',
    appId: '1:1076895934039:web:06c73c01c28fb7eda76512',
    messagingSenderId: '1076895934039',
    projectId: 'umair-liaqat',
    authDomain: 'umair-liaqat.firebaseapp.com',
    storageBucket: 'umair-liaqat.firebasestorage.app',
    measurementId: 'G-PFQS82SRP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpka-oAc82N7aqx1XjDCKU_-aBEYY5w6Q',
    appId: '1:1076895934039:android:2e4f019efa5b5a7fa76512',
    messagingSenderId: '1076895934039',
    projectId: 'umair-liaqat',
    storageBucket: 'umair-liaqat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00mS4D-3RRPZwLcoT4_Sr729UM9OqvPo',
    appId: '1:1076895934039:ios:36503e509867b67ea76512',
    messagingSenderId: '1076895934039',
    projectId: 'umair-liaqat',
    storageBucket: 'umair-liaqat.firebasestorage.app',
    iosBundleId: 'com.example.umairLiaqat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00mS4D-3RRPZwLcoT4_Sr729UM9OqvPo',
    appId: '1:1076895934039:ios:36503e509867b67ea76512',
    messagingSenderId: '1076895934039',
    projectId: 'umair-liaqat',
    storageBucket: 'umair-liaqat.firebasestorage.app',
    iosBundleId: 'com.example.umairLiaqat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7YyzxISjm8Jrl-9MTnPV84fJ8UBwSJCU',
    appId: '1:1076895934039:web:130954a7b6e80644a76512',
    messagingSenderId: '1076895934039',
    projectId: 'umair-liaqat',
    authDomain: 'umair-liaqat.firebaseapp.com',
    storageBucket: 'umair-liaqat.firebasestorage.app',
    measurementId: 'G-4YW261TY9B',
  );
}
