// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2uGYwKbni-eaqlE21xVzwtC846COIlm4',
    appId: '1:943070638712:web:e79b4d3171ca21c07a338d',
    messagingSenderId: '943070638712',
    projectId: 'umairliaqat-d2de2',
    authDomain: 'umairliaqat-d2de2.firebaseapp.com',
    storageBucket: 'umairliaqat-d2de2.firebasestorage.app',
    measurementId: 'G-MP5J4S4SRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUlyer9zVyDU-m1IDCwIlq4HXDdMams6U',
    appId: '1:943070638712:android:5256b98d282e33097a338d',
    messagingSenderId: '943070638712',
    projectId: 'umairliaqat-d2de2',
    storageBucket: 'umairliaqat-d2de2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIktjqAMMoMNyokExPdlHRkXfoylsMeHA',
    appId: '1:943070638712:ios:99cd7ffa27db37187a338d',
    messagingSenderId: '943070638712',
    projectId: 'umairliaqat-d2de2',
    storageBucket: 'umairliaqat-d2de2.firebasestorage.app',
    iosBundleId: 'com.example.umairLiaqatPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIktjqAMMoMNyokExPdlHRkXfoylsMeHA',
    appId: '1:943070638712:ios:99cd7ffa27db37187a338d',
    messagingSenderId: '943070638712',
    projectId: 'umairliaqat-d2de2',
    storageBucket: 'umairliaqat-d2de2.firebasestorage.app',
    iosBundleId: 'com.example.umairLiaqatPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2uGYwKbni-eaqlE21xVzwtC846COIlm4',
    appId: '1:943070638712:web:b8e8a656bbb0c7a17a338d',
    messagingSenderId: '943070638712',
    projectId: 'umairliaqat-d2de2',
    authDomain: 'umairliaqat-d2de2.firebaseapp.com',
    storageBucket: 'umairliaqat-d2de2.firebasestorage.app',
    measurementId: 'G-VE18B7BKDY',
  );

}